// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaVfsLvrlia2jEGNPSD2V7DAPqvvzZ9kI',
    appId: '1:781678478298:web:b9b4b4287501fe5f07f6e3',
    messagingSenderId: '781678478298',
    projectId: 'chat-app-fe05e',
    authDomain: 'chat-app-fe05e.firebaseapp.com',
    databaseURL: 'https://chat-app-fe05e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-fe05e.appspot.com',
    measurementId: 'G-NG0NEPS9Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2C1cKclb9a7ZeDdplbY8h6X-O2mgYLNA',
    appId: '1:781678478298:android:b23f92944b9bb55e07f6e3',
    messagingSenderId: '781678478298',
    projectId: 'chat-app-fe05e',
    databaseURL: 'https://chat-app-fe05e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-fe05e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUBixoQJmt4zR2LGTpPSX-QKrLcj8pvI',
    appId: '1:781678478298:ios:4dac2d36864d4eb807f6e3',
    messagingSenderId: '781678478298',
    projectId: 'chat-app-fe05e',
    databaseURL: 'https://chat-app-fe05e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-fe05e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUBixoQJmt4zR2LGTpPSX-QKrLcj8pvI',
    appId: '1:781678478298:ios:4dac2d36864d4eb807f6e3',
    messagingSenderId: '781678478298',
    projectId: 'chat-app-fe05e',
    databaseURL: 'https://chat-app-fe05e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-fe05e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaVfsLvrlia2jEGNPSD2V7DAPqvvzZ9kI',
    appId: '1:781678478298:web:74a1e69eabd8e6a507f6e3',
    messagingSenderId: '781678478298',
    projectId: 'chat-app-fe05e',
    authDomain: 'chat-app-fe05e.firebaseapp.com',
    databaseURL: 'https://chat-app-fe05e-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-fe05e.appspot.com',
    measurementId: 'G-10YDY38TNB',
  );

}